remote_theme: marella/jekyll-theme-documentation

permalink: pretty
baseurl: "/grant-writing-accelerator"
title: "Grant Writing Accelerator"
description: "Using AI to Accelerate Your Grant Writing"

nav:
- Why HPC (slides): ./why-hpc.pdf
- Tapis / HPC Demo: ./tapis-hpc-demo
- Do It Yourself: ./walkthrough
- Your Workspace: ./your-workspace
- Explore the Compute: ./explore-compute
- Resources: ./resources
